### PR TITLE
Deleted the orphan instances of  bumped lower bound to

### PR DESCRIPTION
**Pull request by waivio**
Bump `hashable`, and delete orphans.
`hashable` lower limit goes to `hashable-1.3.4.0`

### CODE REVIEW

**Comment by facundominguez** [comment]
Thanks @waivio!

The approach works for me, but note that this won't build in CI because `stack.yaml` doesn't include the needed version of `hashable`. I think you could test it in your fork by enabling github actions there.

Then projects using `rest-rewrite` will need to update their `stack.yaml` files accordingly.

Another option would be to drop the instances without changing the package bounds. In this case, it is necessary to write instances manually for the types `WQO`, `StrictOC`, `EquivalenceClass`, and `PartialOrder`.

**Comment by waivio** [comment]
Your Welcome @facundominguez ,
I'm currently working on trying to get Liquid Haskell to compile with GHC 9.0.2 on the Gentoo Haskell overlay.  My interest in `rest-rewrite` is because it is now a dependency of `liquid-fixpoint`.  Currently as of 2022-03-03 Stackage nightly is using `hashable-1.3.5.0`, unfortunately for us the LTS's are still at an older version.  It is definitely possible to get things working with CPP, but it is quite ugly to see it in the code base, especially for a library as young as this one.

How do we weigh backwards compatibility and fast evolution in this case?
Should I make a change in the stack.yaml of `hashable-1.3.5.0` or greater, for both `rest-rewrite` and `liquid-fixpoint`?

**Comment by facundominguez** [comment]
If newer `hashable`s build with ghc-8.10.7, then it could be fine to use a newer nightly snapshot or to list `hashable-1.3.5.0` in `extra-deps`. While liquidhaskell uses ghc-8.10.7, we'd need to worry about using a solution which is compatible with it.

I would try to avoid using CPP. If necessary, I think we could avoid it by defining manual instances for WQO, StrictOC, EquivalenceClass, and PartialOrder, instead.

**Comment by facundominguez** [comment]
I merged these commits in #12 together with a warning fix. Thank you!

**Pull request closed without merging**
